import type {Metadata} from 'next'
import {Outfit, Sen} from 'next/font/google'
import './globals.css'

const sen = Sen({subsets: ['latin'], display: 'swap', variable: '--font-sen'})
const outfit = Outfit({subsets: ['latin'], display: 'swap', variable: '--font-outfit'})
//const nunito = Nunito({subsets: ['latin'], display: 'swap', variable: '--font-nunito'})
//const play = Play({subsets: ['latin'], display: 'swap', variable: '--font-play', weight: "400"})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={`${sen.variable} ${outfit.variable}`}>{children}</body>
    </html>
  )
}
